[build]
  command = "npm run build --prefix frontend"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_BACKEND_URL = "https://xeno-app.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
